name: "Docker Build and Push"
description: "Build and push Docker image"
inputs:
  tag:
    description: "Docker tag"
    required: true
  username:
    description: "Docker Hub username"
    required: true
  token:
    description: "Docker Hub token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        file: docker/Dockerfile
        tags: ${{ inputs.username }}/saigeqtl:${{ inputs.tag }}
